import Head from 'next/head';

const HomePage: React.FC = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className="container">
      <h1 className="font-bold text-4xl">Hello World!</h1>
    </main>
  </div>
);

export default HomePage;
