import Head from 'next/head';
import { Heading } from '@chakra-ui/react';
import { AppContainer } from '../components/app';

const HomePage: React.FC = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <AppContainer py={2}>
      <Heading size="xl">Hello World!</Heading>
    </AppContainer>
  </div>
);

export default HomePage;
